In [3]:
# Project 4 -- Sarah Liu

In [4]:
# Question 1
import pandas as pd

# 1.1 read and check if csv properly loaded by display head
myDf = pd.read_csv('/anvil/projects/tdm/data/titanic/titanic.csv')
myDf.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# show details of columns and vals
myDf.info()
myDf.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
# 1.2 create list of my_names (just names) and list of my_ages (just ages) 
my_names = myDf['Name']
my_ages = myDf['Age']
newList = list(my_names) + list(my_ages) #ceate new list combining name and age

In [7]:
# 1.3 smaller df of jsut name and age 
DFna = myDf[['Name', 'Age']]
DFna.head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [8]:
# Question 2

In [9]:
# 2.1 get name and age of 45 passenger (indexing 44) 
name_45 = my_names[44]
age_44 = my_ages[44]
print(f'45th passenger: {name_45} , {age_44}')

45th passenger: Devaney, Miss. Margaret Delia , 19.0

In [10]:
# 2.2 
my_ages.dtype

dtype('float64')

In [11]:
my_names.dtype

dtype('O')

In [12]:
# my_ages = float data type
# my_names = ''object -> string data type

In [13]:
# 2.3 
my_selection = my_ages < 20
my_result = my_names[my_selection] + ", age " + my_ages[my_selection].astype(str)
display(my_result)

7             Palsson, Master. Gosta Leonard, age 2.0
9       Nasser, Mrs. Nicholas (Adele Achem), age 14.0
10           Sandstrom, Miss. Marguerite Rut, age 4.0
14     Vestrom, Miss. Hulda Amanda Adolfina, age 14.0
16                      Rice, Master. Eugene, age 2.0
                            ...
855              Aks, Mrs. Sam (Leah Rosen), age 18.0
869          Johnson, Master. Harold Theodor, age 4.0
875        Najib, Miss. Adele Kiamie "Jane", age 15.0
877                    Petroff, Mr. Nedelio, age 19.0
887            Graham, Miss. Margaret Edith, age 19.0
Length: 164, dtype: object

In [14]:
# Question 3
myDf['Status'] = myDf['Survived'].map({0: "Dead", 1: "Alive"})

# 3.1 show the value counts for status
print(myDf['Status'].value_counts())

Status
Dead     549
Alive    342
Name: count, dtype: int64

In [15]:
# 3.2 Combine status + sex w/ ,
myDf['Combined'] = myDf['Status'].str.cat(myDf['Sex'], sep=", ")

#display
print(myDf['Combined'].value_counts())

Combined
Dead, male       468
Alive, female    233
Alive, male      109
Dead, female      81
Name: count, dtype: int64

In [16]:
# 3.3 i used the map method to add labels to the survived columns

In [17]:
# Question 4 
# 4.1 get youngest and oldest passenger and show
print('youngest:', myDf['Age'].min())
print('oldest:', myDf['Age'].max())

youngest: 0.42
oldest: 80.0

In [18]:
# list of 'old ages'
old_ages = [61, 62, 63, 64, 65, 66, 70, 70.5, 71, 74, 80]

# .isin() to find 'old ages' in the Age column
old = myDf[myDf["Age"].isin(old_ages)]["Age"]

# 4.2 show count of ppl of old age
print(old.value_counts())

Age
62.0    4
61.0    3
65.0    3
70.0    2
71.0    2
63.0    2
64.0    2
66.0    1
70.5    1
80.0    1
74.0    1
Name: count, dtype: int64

In [19]:
# ages <= 10
my_list1 = list(myDf[myDf['Age'] <= 10]['Age'])
# ages > 10 and <= 60
my_list2 = list(myDf[(myDf['Age'] > 10) & (myDf['Age'] <= 60)]['Age'])

# 4.3 'people' = list1 + list2
people = my_list1 + my_list2
display(len(people)) # number of ppl <= 10 + > 10 and <=60

692

In [33]:
# Question 5
# 5.1 list children, young, adult in age column
children = list(myDf[myDf['Age'] <= 20]['Age'])
young = list(myDf[(myDf['Age'] > 20) & (myDf['Age'] <= 40)]['Age'])
adult = list(myDf[(myDf['Age'] > 40) & (myDf['Age'] <= 60)]['Age'])

print(len(children)) # check list

179

In [38]:
# 5.2 creating age_group column
myDf.loc[myDf["Age"].isin(children), "AgeGroup"] = "Child"
myDf.loc[myDf["Age"].isin(young), "AgeGroup"] = "Young"
myDf.loc[myDf["Age"].isin(adult), "AgeGroup"] = "Adult"
myDf.loc[myDf["Age"].isin(old), "AgeGroup"] = "Old"

print(myDf["AgeGroup"].value_counts()) # check values in AgeGroup

AgeGroup
Young    385
Child    179
Adult    128
Old       22
Name: count, dtype: int64

In [36]:
# 5.3 using crosstab to cobine AgeGroup + Combined
age_analysis = pd.crosstab(myDf["AgeGroup"], myDf["Combined"])
display(age_analysis) # display

Combined  Alive, female  Alive, male  Dead, female  Dead, male
AgeGroup
Adult                34           16            11          67
Child                53           29            24          73
Old                   3            2             0          17
Young               107           46            29         203