In [16]:
import pandas as pd

# Q1

In [17]:
video_games= pd.read_csv('/anvil/projects/tdm/data/grouping/vgchartz-2024.csv')
video_games.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [18]:
# 1.1 group games by genre and calculate the mean of the critic score
genre = video_games.groupby("genre", as_index=False)["critic_score"].mean()
# sort then display top 5 genres with highest avg critic scores
genre.sort_values("critic_score", ascending=False).head()

# highest critic score is sandbox

           genre  critic_score
14       Sandbox      9.200000
19  Visual Novel      8.500000
8          Music      7.992593
6            MMO      7.781818
4      Education      7.750000

In [19]:
# 1.2 group by console and total num of sales
console = video_games.groupby("console", as_index=False)["total_sales"].sum()
# sort total sales then display consols with highest number of sales 
console.sort_values("total_sales", ascending=False).head()

# highest number of console sales is PS2

   console  total_sales
53     PS2      1027.76
73    X360       859.79
54     PS3       839.70
52      PS       546.25
55     PS4       539.92

1.3 
Grouping data is a good way to organize large datasets into smaller, more specific categories. For example, in this case by genre or console. Then we can apply other functions like sum() or mean() to these groups to see trends in these specified categories instead of looking at the entire list at once. It's useful for summarizing thousands of rows of raw data into smaller, more manageable stuff.

# Q2

In [20]:
# 2.1 high_rated column T if score >= 7
video_games['high_rated'] = video_games['critic_score'] >= 7
# low_rated column T = if score < 7
video_games['low_rated'] = video_games['critic_score'] < 7

# display the value counts for both
display(video_games['high_rated'].value_counts())
display(video_games['low_rated'].value_counts())

video_games['critic_score'].isna().sum()

high_rated
False    59689
True      4327
Name: count, dtype: int64

low_rated
False    61665
True      2351
Name: count, dtype: int64

np.int64(57338)

In [21]:
#2.1 filter df to genre = sports and highrated = true
sports_hits = video_games[(video_games['genre'] == 'Sports') & (video_games['high_rated'] == True)]
# display games with a critic score of 9.5
sports_hits[sports_hits['critic_score'] == 9.5]

# Games with critic score of exactly 9.5: Madden NFL 2004 and 2005, SSX 3

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update,high_rated,low_rated
75,/games/boxart/1473680ccc.jpg,Madden NFL 2004,PS2,Sports,EA Sports,EA Tiburon,9.5,5.23,4.26,0.01,0.26,0.71,2003-08-12,NaN,True,False
114,/games/boxart/4564394ccc.jpg,Madden NFL 2005,PS2,Sports,EA Sports,EA Tiburon,9.5,4.53,4.18,0.01,0.26,0.08,2004-08-09,NaN,True,False
4359,/games/boxart/8490939ccc.jpg,SSX 3,GC,Sports,EA Sports BIG,EA Canada,9.5,0.38,0.29,NaN,0.08,0.01,2003-10-20,NaN,True,False

In [22]:
# 2.3 sports failed dataframe 
sports_fails = video_games[(video_games['genre'] == 'Sports') & (video_games['low_rated'] == True)]
# display games w critic score of 2.8
sports_fails[sports_fails['critic_score'] == 2.8]

# games with critic score of exactly 2.8: Major League Baseball 2k10, MLB Slam!

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update,high_rated,low_rated
8292,/games/boxart/full_554728AmericaFrontccc.jpg,Major League Baseball 2K10,DS,Sports,2K Sports,Visual Concepts,2.8,0.15,0.14,NaN,NaN,0.01,2010-03-02,NaN,False,True
59297,/games/boxart/full_mlb-slam_460AmericaFront.jpg,MLB Slam!,NGage,Sports,THQ,THQ,2.8,NaN,NaN,NaN,NaN,NaN,2008-10-31,NaN,False,True

# Q3

In [23]:
# 3.1 genre_counts = genre and num of titles in genre
genre_counts = video_games.groupby("genre", as_index=False)["title"].size()
# rename coulumn to game_count
genre_counts = genre_counts.rename(columns={"size": "game_count"})
# sort by number of games 
genre_counts = genre_counts.sort_values(by="game_count", ascending=False)

In [24]:
# 3.2 show first 10 rows 
genre_counts.head(10) 

# Misc genre has most games listed in dataset

           genre  game_count
7           Misc        9304
0         Action        8557
2      Adventure        6260
13  Role-Playing        5721
17        Sports        5586
15       Shooter        5410
10      Platform        4001
18      Strategy        3685
11        Puzzle        3521
12        Racing        3425

In [25]:
# 3.3 grouping console + genre -> use .size() - get num of games for each combo
console_genre_counts = video_games.groupby(["console", "genre"], as_index=False).size()
# show first 5 rows 
console_genre_counts.head()

  console      genre  size
0    2600     Action   302
1    2600  Adventure     3
2    2600   Fighting     3
3    2600       Misc    21
4    2600   Platform    17

# Q4

In [26]:
app_store = pd.read_csv('/anvil/projects/tdm/data/grouping/googleplaystore.csv')
pd.set_option('display.max_columns', None)

In [29]:
app_store["Clean_Reviews"] = app_store["Reviews"].str.replace(",", "", regex=False)

ValueError: could not convert string to float: '3.0M'

In [ ]:
# 3.1 'M' is causing the error

In [30]:
app_store["Numeric_Reviews"] = app_store["Clean_Reviews"].astype(float)

ValueError: could not convert string to float: '3.0M'

In [35]:
# 4.2 remove 3.0 value
app_store = app_store[app_store["Clean_Reviews"] != "3.0M"]

# convert the column to float
app_store["Numeric_Reviews"] = app_store["Clean_Reviews"].astype(float)

In [36]:
# new column for rating per review = rating / num reviews
app_store['rating_per_review'] = app_store['Rating'] / app_store['Numeric_Reviews']

# 4.3 display head
app_store['rating_per_review'].head()

0    0.025786
1    0.004033
2    0.000054
3    0.000021
4    0.004447
Name: rating_per_review, dtype: float64

# Q5

In [46]:
# 5.1 show unique conent rating values
app_store['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [55]:
# 5.2 show first 5 entries of new content rating
app_store['New_Content_Ratings'] = app_store['Content Rating'].str.upper()
app_store['New_Content_Ratings'].head()

0    EVERYONE
1    EVERYONE
2    EVERYONE
3        TEEN
4    EVERYONE
Name: New_Content_Ratings, dtype: object

In [ ]:
# app_store['New_Content_Rating'] = app_store['Content Rating'].str.lower()

In [57]:
# 5.3 count and sort new content rating by 'App' 
category_counts = app_store.groupby('New_Content_Ratings')['App'].count()
category_counts.sort_values(ascending=False)

# Most Apps in category EVERYONE

New_Content_Ratings
EVERYONE           8714
TEEN               1208
MATURE 17+          499
EVERYONE 10+        414
ADULTS ONLY 18+       3
UNRATED               2
Name: App, dtype: int64